

services:
  backend:
    container_name: backend2_ctr
    image: backend2_img:latest
    build:
      context: ./backend2
      dockerfile: Dockerfile
    ports:
      - "8882:8857"
    #volumes:
    #  - ./backend:/app
    #depends_on:
    #  - mssql_db
    environment:
      DB_HOST: mssql_db
      DB_USER: sa
      DB_PASSWORD: Admin@123.
      DB_NAME: devappDB
    networks:
      - app-network

networks:
  app-network:
    external: true


# Before running the services, create the external network
# >> docker network create app-network